export const SET_SKIN="SET_SKIN";
export const UPDATE_SKIN="UPDATE_SKIN";

export const SET_CONTACT="SET_CONTACT";
export const UPDATE_CONTACT="UPDATE_CONTACT";

export const SET_EDUCATION="SET_EDUCATION";
export const UPDATE_EDUCATION="UPDATE_EDUCATION";

export const REGISTER_REQ="REGISTER_REQ";
export const REGISTER_SUCC="REGISTER_SUCC";
export const REGISTER_FAIL="REGISTER_FAIL";

export const SIGN_IN_REQ="SIGN_IN_REQ";
export const  SIGN_IN_SUCC="SIGN_IN_SUCC";
export const SIGN_IN_FAIL="SIGN_IN_FAIL";

export const SIGN_OUT_REQ="SIGN_OUT_REQ";
export const  SIGN_OUT_SUCC="SIGN_OUT_SUCC";
export const SIGN_OUT_FAIL="SIGN_OUT_FAIL";

export const REMOVE_ERROR="REMOVE_ERROR";



